function products() {
  return [
    {
      id: 1,
      color: 'Коричневый',
      stars: 5.0,
      sale: -9000,
      src: '1',
      srcSchematic: '1s',
      name: 'Кресло велюровое',
      model: ['Кресла', 'Мягкие', 'X-24'],
      price: 24990,
    },
    {
      id: 2,
      color: 'Белый',
      stars: 5.0,
      sale: -10000,
      src: '2',
      srcSchematic: '2s',
      name: 'Диван тканевый',
      model: ['Диваны', 'Прямые', 'Z-44'],
      price: 32990,
    },
    {
      id: 3,
      color: 'Коричневый',
      stars: 5.0,
      sale: -600,
      src: '3',
      srcSchematic: '3s',
      name: 'Будильник',
      model: ['Декор', 'Quartz-23'],
      price: 1290,
    },

    {
      id: 16,
      color: 'Черный',
      stars: 5.0,
      sale: -300,
      src: '16',
      srcSchematic: '16s',
      name: 'Мини-скульптура',
      model: ['Декор', 'Oh my deer'],
      price: 990,
    },
    {
      id: 17,
      color: 'Коричневый',
      stars: 5.0,
      sale: -10000,
      src: '17',
      srcSchematic: '17s',
      name: 'Диван вел-флок',
      model: ['Диваны', 'Z-85'],
      price: 32990,
    },
    {
      id: 18,
      color: 'Коричневый',
      stars: 5.0,
      sale: -700,
      src: '18',
      srcSchematic: '18s',
      name: 'Термометр + гидрометр',
      model: ['Декор', 'H-18'],
      price: 2090,
    },

    {
      id: 4,
      color: 'Черный',
      stars: 5.0,
      sale: 0,
      src: '4',
      srcSchematic: '4s',
      name: 'Диван кожаный',
      model: ['Диваны', 'Прямые', 'R-94'],
      price: 94990,
    },
    {
      id: 5,
      color: 'Коричневый',
      stars: 4.9,
      sale: 0,
      src: '5',
      srcSchematic: '5s',
      name: 'Диван апартековый',
      model: ['Диваны', 'Прямые', 'T-75'],
      price: 69990,
    },
    {
      id: 6,
      color: 'Синий',
      stars: 4.8,
      sale: 0,
      src: '6',
      srcSchematic: '6s',
      name: 'Диван тканевый',
      model: ['Диваны', 'Прямые', 'D-31'],
      price: 28490,
    },
    {
      id: 7,
      color: 'Оранжевый',
      stars: 4.8,
      sale: 0,
      src: '7',
      srcSchematic: '7s',
      name: 'Диван велюровый',
      model: ['Диваны', 'Прямые', 'Y-68'],
      price: 22990,
    },
    {
      id: 8,
      color: 'Желтый',
      stars: 4.8,
      sale: 0,
      src: '8',
      srcSchematic: '8s',
      name: 'Диван из шинила',
      model: ['Диваны', 'Прямые', 'W-95'],
      price: 22990,
    },
    {
      id: 9,
      color: 'Желтый',
      stars: 4.8,
      sale: 0,
      src: '9',
      srcSchematic: '9s',
      name: 'Диван флоковый',
      model: ['Диваны', 'Прямые', 'G-41'],
      price: 22990,
    },
    {
      id: 13,
      color: 'Синий',
      stars: 4.5,
      sale: 0,
      src: '13',
      srcSchematic: '13s',
      name: 'Диван велюровый ',
      model: ['Диваны', 'Прямые', 'R-85'],
      price: 34990,
    },
    {
      id: 14,
      color: 'Синий',
      stars: 4.6,
      sale: 0,
      src: '14',
      srcSchematic: '14s',
      name: 'Диван флоковый',
      model: ['Диваны', 'Прямые', 'H-58'],
      price: 23990,
    },
    {
      id: 15,
      color: 'Синий',
      stars: 4.5,
      sale: 0,
      src: '15',
      srcSchematic: '15s',
      name: 'Диван велюровый',
      model: ['Диваны', 'Прямые', 'S-44'],
      price: 19990,
    },
    {
      id: 10,
      color: 'Синий',
      stars: 4.8,
      sale: 0,
      src: '10',
      srcSchematic: '10s',
      name: 'Диван шиниловый',
      model: ['Диваны', 'Прямые', 'V-43'],
      price: 19990,
    },
    {
      id: 11,
      color: 'Коричневый',
      stars: 4.7,
      sale: 0,
      src: '11',
      srcSchematic: '11s',
      name: 'Диван велюровый',
      model: ['Диваны', 'Прямые', 'V-43'],
      price: 19990,
    },
    {
      id: 12,
      color: 'Зеленый',
      stars: 4.7,
      sale: 0,
      src: '12',
      srcSchematic: '12s',
      name: 'Диван из кожзама',
      model: ['Диваны', 'Прямые', 'F-85'],
      price: 26990,
    },
  ];
}

function categories() {
  return [
    {
      id: 'sofas',
      models: ['Прямые', 'Угловые', 'Модульные'],
      name: 'Диваны',
      src: 'sofas',
    },
    {
      id: 'chairs',
      models: ['Мягкие', 'Кресла-кровати'],
      name: 'Кресла',
      src: 'chairs',
    },
    {
      id: 'beds',
      models: ['Односпальные', 'Двуспальные'],
      name: 'Кровати',
      src: 'beds',
    },
    {
      id: 'curbstones',
      models: ['Тумбы', 'Комоды'],
      name: 'Тумбы и&nbsp;камоды',
      src: 'curbstones',
    },
    {
      id: 'stools',
      models: ['Деревянные', 'Металлокаркас'],
      name: 'Стулья',
      src: 'stools',
    },
  ];
}

function usefuls() {
  return [
    {
      src: 'room',
      descr:
        'И нет сомнений, что сделанные на базе интернет-аналитики выводы представляют собой не что иное?',
    },
    {
      src: 'table-and-chair',
      descr:
        'Как принято считать, некоторые особенности приносят несомненную пользу обществу?',
    },
    {
      src: 'flowers',
      descr:
        'Ясность нашей позиции очевидна: укрепление и развитие внутренней структуры?',
    },
    {
      src: 'kitchen',
      descr:
        'Прежде всего, консультация с широким активом однозначно фиксирует необходимость распределения?',
    },
    {
      src: 'mirror',
      descr:
        'Как принято считать, некоторые особенности приносят несомненную пользу обществу?',
    },
  ];
}
